# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shinfray <shinfray@student.s19.be>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/24 10:18:42 by shinfray          #+#    #+#              #
#    Updated: 2023/07/24 10:18:46 by shinfray         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= micro_paint
CFLAGS= -Wall -Wextra -Werror
RM= rm -rf

all: ${NAME}

${NAME}: ${SRCS}

fclean:
	${RM} ${NAME}

re: fclean all

.phony: all fclean re
